// example/js/webfs-vue/source/components/Item.vue
<template>
  <a v-on:click="click()">
    <img :src="previewUrl()" alt="preview" />
    <br>
    <b>{{ name }}</b>
    <br>
    {{ type == 'directory' ? 'open directory' : `download ${size}` }}
  </a>
</template>

<script>
import { makeLink } from './Api.js'

export default {
  name: 'Item',
  props: [
    'name',
    'type',
    'size',
    'path',
    'openDirectory',
  ],
  methods: {
    click() {
      if (this.type == 'directory')
        return this.openDirectory()
      
      console.log('Open', this.path, 'in new window')
      window.open(makeLink('content', this.path))
    },
    previewUrl() {
      switch (this.type) {
        case 'directory': return '/images/directory.png'
        case 'image': return makeLink('preview', this.path)
        default: return '/images/file.png'
      }
    }
  }
}
</script>

// example/js/webfs-ng/src/app/item/item.component.ts
import { Component, Input, OnInit } from '@angular/core'

import { ApiService, Item } from '../api.service'

@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})
export class ItemComponent implements OnInit {
  @Input() data: Item
  @Input() parent: string[]
  private _previewUrl: string;
  constructor(private _api: ApiService) {}
  
  ngOnInit() {
    switch (this.data.type) {
      case 'directory': 
        this._previewUrl = '/assets/directory.png'
        break;
      case 'image':
        this._previewUrl = this._api.previewPath(this.parent.concat([this.data.name]))
        break;
      default:
        this._previewUrl = '/assets/file.png'
        break;
    }
  }
}

<div class="item">
    <img [src]="_previewUrl" alt="preview">
    <br/>
    <b>{{data.name}}</b>
    <br/>
    {{data.type == 'directory' ? '[directory]' : data.size}}
</div>
